version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:8.1.4
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: test
          command: npm test